$dict_info = {
    'cs' => {'type' => 'write', 'label'=>'Czech', pos=>['subst', 'verb', 'pron', 'num', 'konj', 'part', 'adj', 'adv', 'prep', 'int']},
    'en' => {'type' => 'write', 'label'=>'English', pos=>['subst', 'verb', 'pron', 'num', 'konj', 'part', 'adj', 'adv', 'prep', 'int']},
    'sj' => {'type' => 'write', 'label'=>'Slovak', pos=>['subst', 'verb', 'pron', 'num', 'konj', 'part', 'adj', 'adv', 'prep', 'int']},
    'de' => {'type' => 'write', 'label'=>'German', pos=>['subst', 'verb', 'pron', 'num', 'konj', 'part', 'adj', 'adv', 'prep', 'int']},
    'czj' => {'type' => 'sign', 'label'=>'ČZJ', 'search_in'=>'cs', pos=>['subst', 'verb', 'modif', 'pron', 'num', 'konj', 'part', 'taz', 'kat', 'klf', 'spc']},
    'spj' => {'type' => 'sign', 'label'=>'SPJ', 'search_in'=>'sj', pos=>['subst', 'verb', 'modif', 'pron',
'num', 'konj', 'part', 'taz', 'kat', 'klf', 'spc']},
    'asl' => {'type' => 'sign', 'label'=>'ASL', 'search_in'=>'en', pos=>['subst', 'verb', 'modif', 'pron',
'num', 'konj', 'part', 'taz', 'kat', 'klf', 'spc']},
    'is' => {'type' => 'sign', 'label'=>'IS', 'search_in'=>'en', pos=>['subst', 'verb', 'modif', 'pron',
'num', 'konj', 'part', 'taz', 'kat', 'klf', 'spc']},
    'ogs' => {'type' => 'sign', 'label'=>'OGS', 'search_in'=>'de', pos=>['subst', 'verb', 'modif', 'pron',
'num', 'konj', 'part', 'taz', 'kat', 'klf', 'spc']},
  }
