name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy-view:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run on view
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/private.key
          chmod 400 ~/.ssh/private.key
          ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@www.dictio.info "cd /srv/dictio; GIT_SSH_COMMAND='ssh -i ~/.ssh/github' git pull; ./restart.sh"
  deploy-edit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run on edit
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/private.key
          chmod 400 ~/.ssh/private.key
          ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@edit.dictio.info "cd /srv/dictio; GIT_SSH_COMMAND='ssh -i ~/.ssh/github' git pull; ./restart.sh"
  deploy-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run on admin
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/private.key
          chmod 400 ~/.ssh/private.key
          ssh -i ~/.ssh/private.key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@admin.dictio.info "cd /srv/dictio; GIT_SSH_COMMAND='ssh -i ~/.ssh/github' git pull; ./restart.sh"
